import parseMax from 'libphonenumber-js/max'

export const getCountryOnNumInput = (number,selected) =>{
	const aboutNumber = parseMax(number)
	if(aboutNumber?.country){
		const detectedOrigin = countryList.find((itmCountry)=>{return(itmCountry.code===aboutNumber.country)})
		if(detectedOrigin){
			return({flag:detectedOrigin.flag, dial_code:detectedOrigin.dial_code})
		}else{
			return({flag:'🌐', dial_code:''})
		}
	}else{
		if(selected.dial_code!==''){
			const regx = new RegExp('^(\\'+selected.dial_code+')(\\d+)?$')
			if(regx.test(number)){
				return({...selected})
			}else{
				return({flag:'🌐', dial_code:''})
			}
		}else{
			return({flag:'🌐', dial_code:''})
		}
	}
}

export const getCountryOnCode = (code) =>{
	const country = countryList.find((itmCountry)=>{return(itmCountry.code===code)})
	return({flag:country.flag, dial_code:country.dial_code, code:country.code})
}

export const getCountryList = (key) =>{
	const searchResult = countryList.filter((itmCountry)=>{return(itmCountry.name.toLowerCase().includes(key.toLowerCase()))})
	return(searchResult)
}

export const countryList = [
	{ label: "Afghanistan", dial_code: "+93", code: "AF", flag: "🇦🇫" },
	{ label: "Åland Islands", dial_code: "+358", code: "AX", flag: "🇦🇽" },
	{ label: "Albania", dial_code: "+355", code: "AL", flag: "🇦🇱" },
	{ label: "Algeria", dial_code: "+213", code: "DZ", flag: "🇩🇿" },
	{ label: "American Samoa",dial_code: "+1684", code: "AS", flag: "🇦🇸" },
	{ label: "Andorra", dial_code: "+376", code: "AD", flag: "🇦🇩" },
	{ label: "Angola", dial_code: "+244", code: "AO", flag: "🇦🇴" },
	{ label: "Anguilla", dial_code: "+1264", code: "AI", flag: "🇦🇮" },
	{ label: "Antarctica", dial_code: "+672", code: "AQ", flag: "🇦🇶" },
	{ label: "Antigua and Barbuda", dial_code: "+1268", code: "AG", flag: "🇦🇬"},
	{ label: "Argentina", dial_code: "+54", code: "AR", flag: "🇦🇷" },
	{ label: "Armenia", dial_code: "+374", code: "AM", flag: "🇦🇲" },
	{ label: "Aruba", dial_code: "+297", code: "AW", flag: "🇦🇼" },
	{ label: "Australia", dial_code: "+61", code: "AU", flag: "🇦🇺" },
	{ label: "Austria", dial_code: "+43", code: "AT", flag: "🇦🇹" },
	{ label: "Azerbaijan", dial_code: "+994", code: "AZ", flag: "🇦🇿" },
	{ label: "Bahamas", dial_code: "+1242", code: "BS", flag: "🇧🇸" },
	{ label: "Bahrain", dial_code: "+973", code: "BH", flag: "🇧🇭" },
	{ label: "Bangladesh", dial_code: "+880", code: "BD", flag: "🇧🇩" },
	{ label: "Barbados", dial_code: "+1246", code: "BB", flag: "🇧🇧" },
	{ label: "Belarus", dial_code: "+375", code: "BY", flag: "🇧🇾" },
	{ label: "Belgium", dial_code: "+32", code: "BE", flag: "🇧🇪" },
	{ label: "Belize", dial_code: "+501", code: "BZ", flag: "🇧🇿" },
	{ label: "Benin", dial_code: "+229", code: "BJ", flag: "🇧🇯" },
	{ label: "Bermuda", dial_code: "+1441", code: "BM", flag: "🇧🇲" },
	{ label: "Bhutan", dial_code: "+975", code: "BT", flag: "🇧🇹" },
	{
		label: "Bolivia",
		dial_code: "+591",
		code: "BO",
		flag: "🇧🇴",
	},
	{
		label: "Bosnia and Herzegovina",
		dial_code: "+387",
		code: "BA",
		flag: "🇧🇦",
	},
	{ label: "Botswana", dial_code: "+267", code: "BW", flag: "🇧🇼" },
	{ label: "Bouvet Island", dial_code: "+47", code: "BV", flag: "🇧🇻" },
	{ label: "Brazil", dial_code: "+55", code: "BR", flag: "🇧🇷" },
	{
		label: "British Indian Ocean Territory",
		dial_code: "+246",
		code: "IO",
		flag: "🇮🇴",
	},
	{
		label: "Brunei Darussalam",
		dial_code: "+673",
		code: "BN",
		flag: "🇧🇳",
	},
	{ label: "Bulgaria", dial_code: "+359", code: "BG", flag: "🇧🇬" },
	{ label: "Burkina Faso", dial_code: "+226", code: "BF", flag: "🇧🇫" },
	{ label: "Burundi", dial_code: "+257", code: "BI", flag: "🇧🇮" },
	{ label: "Cambodia", dial_code: "+855", code: "KH", flag: "🇰🇭" },
	{ label: "Cameroon", dial_code: "+237", code: "CM", flag: "🇨🇲" },
	{ label: "Canada", dial_code: "+1", code: "CA", flag: "🇨🇦" },
	{ label: "Cape Verde", dial_code: "+238", code: "CV", flag: "🇨🇻" },
	{
		label: "Cayman Islands",
		dial_code: "+ 345",
		code: "KY",
		flag: "🇰🇾",
	},
	{
		label: "Central African Republic",
		dial_code: "+236",
		code: "CF",
		flag: "🇨🇫",
	},
	{ label: "Chad", dial_code: "+235", code: "TD", flag: "🇹🇩" },
	{ label: "Chile", dial_code: "+56", code: "CL", flag: "🇨🇱" },
	{ label: "China", dial_code: "+86", code: "CN", flag: "🇨🇳" },
	{
		label: "Christmas Island",
		dial_code: "+61",
		code: "CX",
		flag: "🇨🇽",
	},
	{
		label: "Cocos (Keeling) Islands",
		dial_code: "+61",
		code: "CC",
		flag: "🇨🇨",
	},
	{ label: "Colombia", dial_code: "+57", code: "CO", flag: "🇨🇴" },
	{ label: "Comoros", dial_code: "+269", code: "KM", flag: "🇰🇲" },
	{ label: "Congo", dial_code: "+242", code: "CG", flag: "🇨🇬" },
	{
		label: "Congo",
		dial_code: "+243",
		code: "CD",
		flag: "🇨🇩",
	},
	{ label: "Cook Islands", dial_code: "+682", code: "CK", flag: "🇨🇰" },
	{ label: "Costa Rica", dial_code: "+506", code: "CR", flag: "🇨🇷" },
	{ label: "Cote d'Ivoire", dial_code: "+225", code: "CI", flag: "🇨🇮" },
	{ label: "Croatia", dial_code: "+385", code: "HR", flag: "🇭🇷" },
	{ label: "Cuba", dial_code: "+53", code: "CU", flag: "🇨🇺" },
	{ label: "Cyprus", dial_code: "+357", code: "CY", flag: "🇨🇾" },
	{ label: "Czech Republic", dial_code: "+420", code: "CZ", flag: "🇨🇿" },
	{ label: "Denmark", dial_code: "+45", code: "DK", flag: "🇩🇰" },
	{ label: "Djibouti", dial_code: "+253", code: "DJ", flag: "🇩🇯" },
	{ label: "Dominica", dial_code: "+1767", code: "DM", flag: "🇩🇲" },
	{
		label: "Dominican Republic",
		dial_code: "+1849",
		code: "DO",
		flag: "🇨🇩",
	},
	{ label: "Ecuador", dial_code: "+593", code: "EC", flag: "🇪🇨" },
	{ label: "Egypt", dial_code: "+20", code: "EG", flag: "🇪🇬" },
	{ label: "El Salvador", dial_code: "+503", code: "SV", flag: "🇸🇻" },
	{
		label: "Equatorial Guinea",
		dial_code: "+240",
		code: "GQ",
		flag: "🇬🇶",
	},
	{ label: "Eritrea", dial_code: "+291", code: "ER", flag: "🇪🇷" },
	{ label: "Estonia", dial_code: "+372", code: "EE", flag: "🇪🇪" },
	{ label: "Ethiopia", dial_code: "+251", code: "ET", flag: "🇪🇹" },
	{
		label: "Falkland Islands (Malvinas)",
		dial_code: "+500",
		code: "FK",
		flag: "🇫🇰",
	},
	{ label: "Faroe Islands", dial_code: "+298", code: "FO", flag: "🇫🇴" },
	{ label: "Fiji", dial_code: "+679", code: "FJ", flag: "🇫🇯" },
	{ label: "Finland", dial_code: "+358", code: "FI", flag: "🇫🇮" },
	{ label: "France", dial_code: "+33", code: "FR", flag: "🇫🇷" },
	{ label: "French Guiana", dial_code: "+594", code: "GF", flag: "🇬🇫" },
	{
		label: "French Polynesia",
		dial_code: "+689",
		code: "PF",
		flag: "🇵🇫",
	},
	{
		label: "French Southern Territories",
		dial_code: "+262",
		code: "TF",
		flag: "🇹🇫",
	},
	{ label: "Gabon", dial_code: "+241", code: "GA", flag: "🇬🇦" },
	{ label: "Gambia", dial_code: "+220", code: "GM", flag: "🇬🇲" },
	{ label: "Georgia", dial_code: "+995", code: "GE", flag: "🇬🇪" },
	{ label: "Germany", dial_code: "+49", code: "DE", flag: "🇩🇪" },
	{ label: "Ghana", dial_code: "+233", code: "GH", flag: "🇬🇭" },
	{ label: "Gibraltar", dial_code: "+350", code: "GI", flag: "🇬🇮" },
	{ label: "Greece", dial_code: "+30", code: "GR", flag: "🇬🇷" },
	{ label: "Greenland", dial_code: "+299", code: "GL", flag: "🇬🇱" },
	{ label: "Grenada", dial_code: "+1473", code: "GD", flag: "🇬🇩" },
	{ label: "Guadeloupe", dial_code: "+590", code: "GP", flag: "🇬🇵" },
	{ label: "Guam", dial_code: "+1671", code: "GU", flag: "🇬🇺" },
	{ label: "Guatemala", dial_code: "+502", code: "GT", flag: "🇬🇹" },
	{ label: "Guernsey", dial_code: "+44", code: "GG", flag: "🇬🇬" },
	{ label: "Guinea", dial_code: "+224", code: "GN", flag: "🇬🇳" },
	{ label: "Guinea-Bissau", dial_code: "+245", code: "GW", flag: "🇬🇼" },
	{ label: "Guyana", dial_code: "+592", code: "GY", flag: "🇬🇾" },
	{ label: "Haiti", dial_code: "+509", code: "HT", flag: "🇭🇹" },
	{
		label: "Heard Island and Mcdonald Islands",
		dial_code: "+0",
		code: "HM",
		flag: "🇭🇲",
	},
	{
		label: "Holy See (Vatican City State)",
		dial_code: "+379",
		code: "VA",
		flag: "🇻🇦",
	},
	{ label: "Honduras", dial_code: "+504", code: "HN", flag: "🇭🇳" },
	{ label: "Hong Kong", dial_code: "+852", code: "HK", flag: "🇭🇰" },
	{ label: "Hungary", dial_code: "+36", code: "HU", flag: "🇭🇺" },
	{ label: "Iceland", dial_code: "+354", code: "IS", flag: "🇮🇸" },
	{ label: "India", dial_code: "+91", code: "IN", flag: "🇮🇳" },
	{ label: "Indonesia", dial_code: "+62", code: "ID", flag: "🇮🇩" },
	{
		label: "Iran",
		dial_code: "+98",
		code: "IR",
		flag: "🇮🇷",
	},
	{ label: "Iraq", dial_code: "+964", code: "IQ", flag: "🇮🇶" },
	{ label: "Ireland", dial_code: "+353", code: "IE", flag: "🇮🇪" },
	{ label: "Isle of Man", dial_code: "+44", code: "IM", flag: "🇮🇲" },
	{ label: "Israel", dial_code: "+972", code: "IL", flag: "🇮🇱" },
	{ label: "Italy", dial_code: "+39", code: "IT", flag: "🇮🇹" },
	{ label: "Jamaica", dial_code: "+1876", code: "JM", flag: "🇯🇲" },
	{ label: "Japan", dial_code: "+81", code: "JP", flag: "🇯🇵" },
	{ label: "Jersey", dial_code: "+44", code: "JE", flag: "🇯🇪" },
	{ label: "Jordan", dial_code: "+962", code: "JO", flag: "🇯🇴" },
	{ label: "Kazakhstan", dial_code: "+7", code: "KZ", flag: "🇰🇿" },
	{ label: "Kenya", dial_code: "+254", code: "KE", flag: "🇰🇪" },
	{ label: "Kiribati", dial_code: "+686", code: "KI", flag: "🇰🇮" },
	{
		label: "North Korea",
		dial_code: "+850",
		code: "KP",
		flag: "🇰🇵",
	},
	{
		label: "South Korea",
		dial_code: "+82",
		code: "KR",
		flag: "🇰🇷",
	},
	{ label: "Kosovo", dial_code: "+383", code: "XK", flag: "🇽🇰" },
	{ label: "Kuwait", dial_code: "+965", code: "KW", flag: "🇰🇼" },
	{ label: "Kyrgyzstan", dial_code: "+996", code: "KG", flag: "🇰🇬" },
	{ label: "Laos", dial_code: "+856", code: "LA", flag: "🇱🇦" },
	{ label: "Latvia", dial_code: "+371", code: "LV", flag: "🇱🇻" },
	{ label: "Lebanon", dial_code: "+961", code: "LB", flag: "🇱🇧" },
	{ label: "Lesotho", dial_code: "+266", code: "LS", flag: "🇱🇸" },
	{ label: "Liberia", dial_code: "+231", code: "LR", flag: "🇱🇷" },
	{
		label: "Libyan Arab Jamahiriya",
		dial_code: "+218",
		code: "LY",
		flag: "🇱🇾",
	},
	{ label: "Liechtenstein", dial_code: "+423", code: "LI", flag: "🇱🇮" },
	{ label: "Lithuania", dial_code: "+370", code: "LT", flag: "🇱🇹" },
	{ label: "Luxembourg", dial_code: "+352", code: "LU", flag: "🇱🇺" },
	{ label: "Macao", dial_code: "+853", code: "MO", flag: "🇲🇴" },
	{ label: "Macedonia", dial_code: "+389", code: "MK", flag: "🇲🇰" },
	{ label: "Madagascar", dial_code: "+261", code: "MG", flag: "🇲🇬" },
	{ label: "Malawi", dial_code: "+265", code: "MW", flag: "🇲🇼" },
	{ label: "Malaysia", dial_code: "+60", code: "MY", flag: "🇲🇾" },
	{ label: "Maldives", dial_code: "+960", code: "MV", flag: "🇲🇻" },
	{ label: "Mali", dial_code: "+223", code: "ML", flag: "🇲🇱" },
	{ label: "Malta", dial_code: "+356", code: "MT", flag: "🇲🇹" },
	{
		label: "Marshall Islands",
		dial_code: "+692",
		code: "MH",
		flag: "🇲🇭",
	},
	{ label: "Martinique", dial_code: "+596", code: "MQ", flag: "🇲🇶" },
	{ label: "Mauritania", dial_code: "+222", code: "MR", flag: "🇲🇷" },
	{ label: "Mauritius", dial_code: "+230", code: "MU", flag: "🇲🇺" },
	{ label: "Mayotte", dial_code: "+262", code: "YT", flag: "🇾🇹" },
	{ label: "Mexico", dial_code: "+52", code: "MX", flag: "🇲🇽" },
	{
		label: "Micronesia",
		dial_code: "+691",
		code: "FM",
		flag: "🇫🇲",
	},
	{ label: "Moldova", dial_code: "+373", code: "MD", flag: "🇲🇩" },
	{ label: "Monaco", dial_code: "+377", code: "MC", flag: "🇲🇨" },
	{ label: "Mongolia", dial_code: "+976", code: "MN", flag: "🇲🇳" },
	{ label: "Montenegro", dial_code: "+382", code: "ME", flag: "🇲🇪" },
	{ label: "Montserrat", dial_code: "+1664", code: "MS", flag: "🇲🇸" },
	{ label: "Morocco", dial_code: "+212", code: "MA", flag: "🇲🇦" },
	{ label: "Mozambique", dial_code: "+258", code: "MZ", flag: "🇲🇿" },
	{ label: "Myanmar", dial_code: "+95", code: "MM", flag: "🇲🇲" },
	{ label: "Namibia", dial_code: "+264", code: "NA", flag: "🇳🇦" },
	{ label: "Nauru", dial_code: "+674", code: "NR", flag: "🇳🇷" },
	{ label: "Nepal", dial_code: "+977", code: "NP", flag: "🇳🇵" },
	{ label: "Netherlands", dial_code: "+31", code: "NL", flag: "🇳🇱" },
	{
		label: "Netherlands Antilles",
		dial_code: "+599",
		code: "AN",
		flag: "🇳🇱",
	},
	{ label: "New Caledonia", dial_code: "+687", code: "NC", flag: "🇳🇨" },
	{ label: "New Zealand", dial_code: "+64", code: "NZ", flag: "🇳🇿" },
	{ label: "Nicaragua", dial_code: "+505", code: "NI", flag: "🇳🇮" },
	{ label: "Niger", dial_code: "+227", code: "NE", flag: "🇳🇪" },
	{ label: "Nigeria", dial_code: "+234", code: "NG", flag: "🇳🇬" },
	{ label: "Niue", dial_code: "+683", code: "NU", flag: "🇳🇺" },
	{ label: "Norfolk Island", dial_code: "+672", code: "NF", flag: "🇳🇫" },
	{
		label: "Northern Mariana Islands",
		dial_code: "+1670",
		code: "MP",
		flag: "🇲🇵",
	},
	{ label: "Norway", dial_code: "+47", code: "NO", flag: "🇳🇴" },
	{ label: "Oman", dial_code: "+968", code: "OM", flag: "🇴🇲" },
	{ label: "Pakistan", dial_code: "+92", code: "PK", flag: "🇵🇰" },
	{ label: "Palau", dial_code: "+680", code: "PW", flag: "🇵🇼" },
	{
		label: "Palestine",
		dial_code: "+970",
		code: "PS",
		flag: "🇵🇸",
	},
	{ label: "Panama", dial_code: "+507", code: "PA", flag: "🇵🇦" },
	{
		label: "Papua New Guinea",
		dial_code: "+675",
		code: "PG",
		flag: "🇵🇬",
	},
	{ label: "Paraguay", dial_code: "+595", code: "PY", flag: "🇵🇾" },
	{ label: "Peru", dial_code: "+51", code: "PE", flag: "🇵🇪" },
	{ label: "Philippines", dial_code: "+63", code: "PH", flag: "🇵🇭" },
	{ label: "Pitcairn", dial_code: "+64", code: "PN", flag: "🇵🇳" },
	{ label: "Poland", dial_code: "+48", code: "PL", flag: "🇵🇱" },
	{ label: "Portugal", dial_code: "+351", code: "PT", flag: "🇵🇹" },
	{ label: "Puerto Rico", dial_code: "+1939", code: "PR", flag: "🇵🇷" },
	{ label: "Qatar", dial_code: "+974", code: "QA", flag: "🇶🇦" },
	{ label: "Romania", dial_code: "+40", code: "RO", flag: "🇷🇴" },
	{ label: "Russia", dial_code: "+7", code: "RU", flag: "🇷🇺" },
	{ label: "Rwanda", dial_code: "+250", code: "RW", flag: "🇷🇼" },
	{ label: "Reunion", dial_code: "+262", code: "RE", flag: "🇫🇷" },
	{
		label: "Saint Barthelemy",
		dial_code: "+590",
		code: "BL",
		flag: "🇧🇱",
	},
	{
		label: "Saint Helena",
		dial_code: "+290",
		code: "SH",
		flag: "🇸🇭",
	},
	{
		label: "Saint Kitts and Nevis",
		dial_code: "+1869",
		code: "KN",
		flag: "🇰🇳",
	},
	{ label: "Saint Lucia", dial_code: "+1758", code: "LC", flag: "🇱🇨" },
	{ label: "Saint Martin", dial_code: "+590", code: "MF", flag: "🇲🇫" },
	{
		label: "Saint Pierre and Miquelon",
		dial_code: "+508",
		code: "PM",
		flag: "🇵🇲",
	},
	{
		label: "Saint Vincent and the Grenadines",
		dial_code: "+1784",
		code: "VC",
		flag: "🇻🇨",
	},
	{ label: "Samoa", dial_code: "+685", code: "WS", flag: "🇼🇸" },
	{ label: "San Marino", dial_code: "+378", code: "SM", flag: "🇸🇲" },
	{
		label: "Sao Tome and Principe",
		dial_code: "+239",
		code: "ST",
		flag: "🇸🇹",
	},
	{ label: "Saudi Arabia", dial_code: "+966", code: "SA", flag: "🇸🇦" },
	{ label: "Senegal", dial_code: "+221", code: "SN", flag: "🇸🇳" },
	{ label: "Serbia", dial_code: "+381", code: "RS", flag: "🇷🇸" },
	{ label: "Seychelles", dial_code: "+248", code: "SC", flag: "🇸🇨" },
	{ label: "Sierra Leone", dial_code: "+232", code: "SL", flag: "🇸🇱" },
	{ label: "Singapore", dial_code: "+65", code: "SG", flag: "🇸🇬" },
	{ label: "Sint Maarten", dial_code: "+1721", code: "SX", flag: "🇸🇽" },
	{ label: "Slovakia", dial_code: "+421", code: "SK", flag: "🇸🇰" },
	{ label: "Slovenia", dial_code: "+386", code: "SI", flag: "🇸🇮" },
	{
		label: "Solomon Islands",
		dial_code: "+677",
		code: "SB",
		flag: "🇸🇧",
	},
	{ label: "Somalia", dial_code: "+252", code: "SO", flag: "🇸🇴" },
	{ label: "South Africa", dial_code: "+27", code: "ZA", flag: "🇿🇦" },
	{ label: "South Sudan", dial_code: "+211", code: "SS", flag: "🇸🇸" },
	{
		label: "South Georgia and the South Sandwich Islands",
		dial_code: "+500",
		code: "GS",
		flag: "🇬🇸",
	},
	{ label: "Spain", dial_code: "+34", code: "ES", flag: "🇪🇸" },
	{ label: "Sri Lanka", dial_code: "+94", code: "LK", flag: "🇱🇰" },
	{ label: "Sudan", dial_code: "+249", code: "SD", flag: "🇸🇩" },
	{ label: "Suriname", dial_code: "+597", code: "SR", flag: "🇸🇷" },
	{
		label: "Svalbard and Jan Mayen",
		dial_code: "+47",
		code: "SJ",
		flag: "🇩🇰",
	},
	{ label: "Swaziland", dial_code: "+268", code: "SZ", flag: "🇸🇿" },
	{ label: "Sweden", dial_code: "+46", code: "SE", flag: "🇸🇪" },
	{ label: "Switzerland", dial_code: "+41", code: "CH", flag: "🇨🇭" },
	{
		label: "Syrian Arab Republic",
		dial_code: "+963",
		code: "SY",
		flag: "🇸🇾",
	},
	{ label: "Taiwan", dial_code: "+886", code: "TW", flag: "🇹🇼" },
	{ label: "Tajikistan", dial_code: "+992", code: "TJ", flag: "🇹🇯" },
	{
		label: "Tanzania",
		dial_code: "+255",
		code: "TZ",
		flag: "🇹🇿",
	},
	{ label: "Thailand", dial_code: "+66", code: "TH", flag: "🇹🇭" },
	{ label: "Timor-Leste", dial_code: "+670", code: "TL", flag: "🇹🇱" },
	{ label: "Togo", dial_code: "+228", code: "TG", flag: "🇹🇬" },
	{ label: "Tokelau", dial_code: "+690", code: "TK", flag: "🇹🇰" },
	{ label: "Tonga", dial_code: "+676", code: "TO", flag: "🇹🇴" },
	{
		label: "Trinidad and Tobago",
		dial_code: "+1868",
		code: "TT",
		flag: "🇹🇹",
	},
	{ label: "Tunisia", dial_code: "+216", code: "TN", flag: "🇹🇳" },
	{ label: "Turkey", dial_code: "+90", code: "TR", flag: "🇹🇷" },
	{ label: "Turkmenistan", dial_code: "+993", code: "TM", flag: "🇹🇲" },
	{
		label: "Turks and Caicos Islands",
		dial_code: "+1649",
		code: "TC",
		flag: "🇹🇨",
	},
	{ label: "Tuvalu", dial_code: "+688", code: "TV", flag: "🇹🇻" },
	{ label: "Uganda", dial_code: "+256", code: "UG", flag: "🇺🇬" },
	{ label: "Ukraine", dial_code: "+380", code: "UA", flag: "🇺🇦" },
	{
		label: "United Arab Emirates",
		dial_code: "+971",
		code: "AE",
		flag: "🇦🇪",
	},
	{ label: "United Kingdom", dial_code: "+44", code: "GB", flag: "🇬🇧" },
	{ label: "United States", dial_code: "+1", code: "US", flag: "🇺🇸" },
	{ label: "Uruguay", dial_code: "+598", code: "UY", flag: "🇺🇾" },
	{ label: "Uzbekistan", dial_code: "+998", code: "UZ", flag: "🇺🇿" },
	{ label: "Vanuatu", dial_code: "+678", code: "VU", flag: "🇻🇺" },
	{
		label: "Venezuela",
		dial_code: "+58",
		code: "VE",
		flag: "🇻🇪",
	},
	{ label: "Vietnam", dial_code: "+84", code: "VN", flag: "🇻🇳" },
	{
		label: "Virgin Islands",
		dial_code: "+1284",
		code: "VG",
		flag: "🇻🇬",
	},
	{
		label: "Virgin Islands",
		dial_code: "+1340",
		code: "VI",
		flag: "🇻🇮",
	},
	{
		label: "Wallis and Futuna",
		dial_code: "+681",
		code: "WF",
		flag: "🇼🇫",
	},
	{ label: "Yemen", dial_code: "+967", code: "YE", flag: "🇾🇪" },
	{ label: "Zambia", dial_code: "+260", code: "ZM", flag: "🇿🇲" },
	{ label: "Zimbabwe", dial_code: "+263", code: "ZW", flag: "🇿🇼" },
];